### ISSUE TITLE
Error when running main.py

### ISSUE THREAD

**Issue by crinkle-cut** [Nixuge/Aurixa#2]
crinklecut@machinations Aurixa % python src/main.py
Traceback (most recent call last):
  File "/Users/crinklecut/Aurixa/src/main.py", line 3, in <module>
    from update import update_tweaks
  File "/Users/crinklecut/Aurixa/src/update.py", line 1, in <module>
    from parsers.parse_all_packages import discover_packages
  File "/Users/crinklecut/Aurixa/src/parsers/parse_all_packages.py", line 4, in <module>
    from datatypes.tweak import Tweak
  File "/Users/crinklecut/Aurixa/src/datatypes/tweak.py", line 88
    description_file.write(f"# {self.get_latest_control().get_property("Name")}\n\nYour description here")
                                                                        ^^^^
SyntaxError: f-string: unmatched '('
crinklecut@machinations Aurixa %

**Comment by Nixuge** [comment]
What Python version are you running? Is it pre 3.11 by any chance?

**Comment by crinkle-cut** [comment]
today i found out that i'm extremely stupid, sorry for wasting your time

**Comment by Nixuge** [comment]
Made things clearer in the readme now it's explicit you need 3.11+
